spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false   #不向注册中心注册自己
    fetch-registry: false         #自己是注册中心，不需要检索服务
